FROM python:3.9.8

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 2

WORKDIR /code

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

version:'3.9.8'

services:
  django:
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    ports:
      -"80:8000"