# Generated by Django 4.1.4 on 2022-12-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0003_alter_cliente_saldo_alter_cliente_servico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='marca',
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='Yamaha', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
